version: '2'
services:
  ui:
    build: ./ui
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - '8081:8081'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'